### ISSUE TITLE
Accordion integration

### ISSUE THREAD

**Issue by gmpf** [contao-bootstrap/card#2]
In Contao Bootstrap for Bootstrap 3, the panel component used to include an integration with the Contao accordion content elements. Bootstrap 4 suggests using cards for accordions: https://getbootstrap.com/docs/4.0/components/collapse/#accordion-example

Is this something that is planned to be integrated here?

I'd happily work on it myself if it's something that would be accepted as a PR, but never having delved too deeply into the Contao Bootstrap code, and given the extensive rewrite between 1 and 2, I'm not so sure what kind of implementation you'd want to see for making the accordion group available in the individual accordion template, i. e. what used to be taken care of by `Netzmacht\Bootstrap\Panel\Helper::preparePanel()`.

**Comment by dmolineus** [comment]
I already got charged to provide a accordion implementation for Contao 4. So there will be a component for bootstrap 4, not later than June this year.

**Comment by dmolineus** [comment]
Meanwhile the panel component is available for Contao 4.
